=== NikiTOSS3000/XMLParsers/src/main/webapp/xml/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epam.com/products"
        xmlns:tns="http://www.epam.com/products" elementFormDefault="qualified">
    <element name="products">
        <complexType>
            <sequence>
                <element name="category" type="tns:category" maxOccurs="unbounded" 
                         minOccurs="1"/>
            </sequence>
        </complexType>
    </element>
    
    <complexType name="category">
        <sequence>
            <element name="subcategory" type="tns:subcategory" maxOccurs="unbounded" 
                     minOccurs="1"/>
        </sequence>
        <attribute name="name" type="string" use="required"/>
    </complexType>
    
    <complexType name="subcategory">
        <sequence>
            <element name="product" type="tns:product" maxOccurs="unbounded" 
                     minOccurs="1"/>
        </sequence>
        <attribute name="name" type="string" use="required"/>
    </complexType>
    
    <complexType name="product">
        <sequence>
            <element name="producer" type="string"/>
            <element name="model" type="tns:model"/>
            <element name="date" type="tns:date"/>
            <element name="color" type="string"/>
            <choice>
                <element name="price" type="integer"/>
                <element name="instock" type="boolean" default="true"/>
            </choice>
        </sequence>
        <attribute name="name" type="string" use="required"/>
    </complexType>
    
    <simpleType name="model">
        <restriction base="string">
            <pattern value="[a-zA-Z]{2}\d{3}"></pattern>
        </restriction>
    </simpleType>
    
    <simpleType name="date">
        <restriction base="string">
            <pattern value="(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[012])-[12][0-9][0-9][0-9]"></pattern>
        </restriction>
    </simpleType>
</schema>

=== NikiTOSS3000/XMLParsers/src/main/webapp/xml/products.xml
<?xml version="1.0"?>
<products xmlns="http://www.epam.com/products"
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
          xsi:schemaLocation="http://www.epam.com/products products.xsd">
    <category name="venicle">
        <subcategory name="cars">
            <product name="BMW">
                <producer>Germany</producer>
                <model>ss111</model>
                <date>24-09-2002</date>
                <color>red</color>
                <instock>false</instock>
            </product>
            <product name="Mercedes">
                <producer>Germany</producer>
                <model>sl666</model>
                <date>10-02-1991</date>
                <color>red</color>
                <price>32000</price>
            </product>
        </subcategory>
        <subcategory name="jeep">
            <product name="Mercedes">
                <producer>Germany</producer>
                <model>sl666</model>
                <date>10-02-1991</date>
                <color>red</color>
                <price>32000</price>
            </product>
        </subcategory>
    </category>
    <category name="pens">
        <subcategory name="roll">
            <product name="SuperPen">
                <producer>Russia</producer>
                <model>sS123</model>
                <date>12-09-2013</date>
                <color>white</color>
                <price>100</price>
            </product>
        </subcategory>
        <subcategory name="gel">
            <product name="Gelic">
                <producer>England</producer>
                <model>AA101</model>
                <date>12-05-2001</date>
                <color>blue</color>
                <price>200</price>
            </product>
        </subcategory>
    </category>
</products>
